version: '3'

services:
  db:
    container_name: db
    image: mysql
    ports:
      - '3308:3306'
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coffeeDb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  apache:
    container_name: apache
    build: ./apache
    volumes:
      - ./apache/src:/var/www/html
    ports:
      - '8001:8001'
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DB: coffeeDB
    links:
      - db
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      #- ./nginx/src:/etc/nginx/src
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '8000:8000'
    links:
      - db