version: "3"

services:
  db:
    image: mysql
    ports:
      - '3308:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: appDB
  server:
    build: ./server
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html